name: isen_aurion_client
description: A dart api that interfaces with the ERP Aurion used by the ISEN.
version: 1.1.0
homepage: https://github.com/sehnryr/isen_aurion_client

environment:
    sdk: ">=2.17.6 <3.0.0"

dependencies:
    requests:
        git:
            url: https://github.com/jossef/requests.git
            ref: cors-credentials
    html: ^0.15.0
    xpath_selector_html_parser: ^3.0.0
    http: ^0.13.5
    meta: ^1.8.0

dev_dependencies:
    lints: ^2.0.0
    test: ^1.16.0
